permissions:
  contents: write

on:
  push:
    branches:
      - dev
      - test
      - prod
    paths:
      - 'L3.json'
      
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy L3 Configuration
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          ref: ${{ github.ref_name }}      
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute L3 Deployment Script
        run: python scripts/l3-deployment.py "L3.json" "${{ secrets.RELTIO_USERNAME }}" "${{ secrets.RELTIO_PASSWORD }}" "${{ secrets.RELTIO_ENVIRONMENT }}" "${{ secrets.RELTIO_TENANT_ID }}" "${{ secrets.RDM_TENANT_ID }}"
